/**
 * DEPRECATED — use scripts/refresh_data.py (via refresh-data.sh).
 * This Node path skips ETag caching, schema validation, and atomic writes.
 *
 * Embed JSON data as a classic script so index.html works via file://
 * (Chrome blocks ES modules + fetch on file://).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = join(root, 'data');
const outPath = join(root, 'js', 'embedded-data.js');

mkdirSync(join(root, 'js'), { recursive: true });

const weapons = JSON.parse(readFileSync(join(dataDir, 'weapons.json'), 'utf8'));
const attachments = JSON.parse(readFileSync(join(dataDir, 'attachments.json'), 'utf8'));
const balance = JSON.parse(readFileSync(join(dataDir, 'balance_tables.json'), 'utf8'));
const ammo = JSON.parse(readFileSync(join(dataDir, 'ammo.json'), 'utf8'));

const payload = { weapons, attachments, balance, ammo };
const body = `/* Auto-generated by scripts/embed-data.mjs — do not edit by hand */\nwindow.BF6_DATA = ${JSON.stringify(payload)};\n`;

writeFileSync(outPath, body);
console.log(`wrote js/embedded-data.js (${body.length} bytes)`);
